#!/bin/bash
# amixer -c 0 set Master "$@" > /dev/null
vol="$(amixer get Master | tail -n1 | sed -r 's/.*\[(.*)%\].*/\1/')"
mute="$(amixer get Master | tail -1 | awk '{print $6}' | sed 's/[^a-z]*//g')"
icon=""
iconmuted="󰝟"
# Arbitrary but unique message tag
# msgTag="myvolume"


if [[ $vol == 0 || "$mute" == "off" ]]; then
    # Show the sound muted notification
    printf "^c#8fbcbb^  %s %s \\n" "$iconmuted" "$vol%^d^"   
    # dunstify -a "changeVolume" -u low -i audio-volume-muted -h string:x-dunst-stack-tag:$msgTag "Volume muted" 
else
    # Show the volume notification
    printf "^c#8fbcbb^  %s %s \\n" "$icon" "$vol%^d^"   
     # dunstify -a "changeVolume" -u low -i audio-volume-high -h string:x-dunst-stack-tag:$msgTag \
     # -h int:value:"$vol" "Volume: ${vol}%"
fi
# canberra-gtk-play -i audio-volume-change -d "changeVolume"
